spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/knowledge_assistant
    username: postgres
    password: PostgreSQL@2026

  ai:
    ollama:
      base-url: http://localhost:11434

      chat:
        model: llama3.2

      embedding:
        model: nomic-embed-text
file:
  upload-dir: D:/knowledge-assistant-filedata