spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  ai:
    model:
      chat: google-genai
      embedding: none
      "embedding.text": google-genai

    google:
      genai:
        api-key: ${GEMINI_API_KEY}

        chat:
          options:
            model: gemini-2.5-flash

        embedding:
          api-key: ${GEMINI_API_KEY}
          text:
            model: text-embedding-004

file:
  upload-dir: uploads